const articles = [
    {
        name: 'eternauta',
        title: 'El Eternauta',
        content: [
            `El Eternauta —Memorias de un navegante del porvenir, subtítulo de su versión original— es una historieta argentina seriada de ciencia ficción creada por el guionista, Héctor Germán Oesterheld​ y el dibujante Francisco Solano López. Publicada desde 1957 hasta 1959 en la revista Hora Cero Semanal, tuvo una reedición con el dibujante Alberto Breccia, interrumpida en 1969 y una segunda parte, conocida como El Eternauta II, publicada en 1976 en la revista Skorpio.`,
            `La trama se centra en una invasión alienígena mediante una tormenta de nieve tóxica que acaba con la mayor parte de la población, y la resistencia de supervivientes en Buenos Aires. Su protagonista es Juan Salvo, El Eternauta, quien en un ejercicio de metaficción narra lo sucedido ante Oesterheld.`,
            `La historieta es considerada entre las más importantes de Argentina y de Latinoamérica. Su edición de 2015 de Fantagraphics Books para Estados Unidos obtuvo tres nominaciones a los Premios Eisner y ganó en la categoría Mejor colección o proyecto de archivo de tiras de prensa.`,
            `A principios de 2020, la plataforma de streaming Netflix anunció la adaptación de El Eternauta en una serie a nivel internacional,​ estrenada el 30 de abril de 2025 y que rápidamente se convirtió en la segunda más vista a nivel global en Netflix. Además, alcanzó el primer puesto entre las series más vistas en habla no inglesa.`,
        ]
    }, {
        name: 'amigos', 
        title: 'Cómo Ganar Amigos E Influir Sobre las Personas',
        content: [
            `Cómo ganar amigos e influir sobre las personas (en la versión original How to Win Friends and Influence People) es un libro escrito por Dale Carnegie, publicado por primera vez en 1936. Ofrece consejos prácticos para mejorar las relaciones interpersonales y la capacidad de liderazgo. Carnegie enfatiza la importancia de no criticar, condenar ni quejarse, sugiriendo en su lugar demostrar aprecio sincero y despertar un deseo vehemente en los demás. Destaca el interés genuino en las personas, el poder de una sonrisa, la importancia de recordar y usar los nombres de las personas, ser un buen oyente, hablar de lo que interesa a los demás y hacer que los demás se sientan importantes.`,
            `Para influir en las personas, el autor recomienda evitar discusiones, respetar las opiniones ajenas, admitir los propios errores, empezar de manera amigable, conseguir que los demás digan "sí" inmediatamente, permitir que la otra persona hable más, hacer que las ideas parezcan propias de los demás, ver las cosas desde su punto de vista, mostrar simpatía, apelar a motivos nobles, dramatizar ideas y lanzar retos. Leon Shimkin, de la firma publicitaria Simon & Schuster tomó uno de los cursos de 14 semanas impartidos por Carnegie en 1934. Shimkin convenció a Carnegie para dejar que un taquígrafo tomara notas de su curso para preparar una publicación.​`, 
            `En el liderazgo, Carnegie sugiere empezar con elogios y aprecio sincero, llamar la atención sobre los errores de manera indirecta, hablar de los propios errores antes de criticar, hacer preguntas en lugar de dar órdenes directas, permitir que las personas salven su prestigio, elogiar el progreso, atribuir buenas reputaciones, alentar y hacer que los errores parezcan fáciles de corregir, y procurar que los demás se sientan satisfechos haciendo lo que uno quiere.`,
            `Estos principios buscan fomentar el respeto mutuo, la empatía y la motivación, creando relaciones más efectivas y armoniosas tanto en el ámbito personal como profesional.`,
        ]
    }, {
        name: 'socialismo',
        title: 'Socialismo, Cálculo Económico y Función Empresarial',
        content: [
            `Socialismo, cálculo económico y función empresarial es un libro de teoría económica y de historia del pensamiento económico escrito por Jesús Huerta de Soto en 1992. Su propósito es explicar por qué el socialismo es a su juicio un error intelectual que había sido destruido teóricamente por varios intelectuales de la escuela austriaca —usando un paradigma subjetivista económico— décadas antes de la caída el bloque socialista en Europa del Este, y que la misma teoría puede aplicarse al presente estado de bienestar.`,
            `En la parte teórica la obra explica el funcionamiento de una economía de mercado usando el concepto de función empresarial —o empresarialidad, la búsqueda de oportunidades de ganancia (subjetiva)— y las características del conocimiento que el autor afirma es necesario para coordinar los procesos productivos. Huerta de Soto elabora esta explicación de la integración de los marcos teóricos de la praxeología de Ludwig von Mises y la economía del conocimiento de Israel Kirzner. A partir de esta base explica la imposibilidad teórica de una productividad coordinada en el socialismo y el intervencionismo de sus diversas variantes y las consecuencias de la aplicación de estos proyectos, así también hace su aportación con una nueva definición del socialismo y el intervencionismo, ya no como la propiedad estatal de los medios de producción, sino como "la agresión institucionalizada al libre ejercicio de la función empresarial" - en parte en respuesta a la definición de socialismo dada por Hans-Hermann Hoppe en su libro A Theory of Socialism and Capitalism.`,
            `En sus capítulos sobre historia, da un repaso al debate sobre el cálculo económico en el socialismo, defendiendo los argumentos dados por Mises en 1920, y las colaboraciones de sus discípulos Friedrich Hayek y Lionel Robbins en el debate. Hace una crítica a las interpretaciones estáticas del proceso económico (propias del paradigma del equilibrio general de la economía neoclásica) que Huerta de Soto afirma desviaron la comprensión de los argumentos de Mises sobre la imposibilidad del cálculo económico sin un sistema de precios de mercado - como en las economías socialistas. Huerta de Soto indica que paradójicamente los economistas marxistas en el debate se valieron del paradigma neoclásico que se basa en la idea de un mercado "perfecto" (idea también criticada en el libro) para poder dar respuestas en el debate. Hace también un recuento y refutaciones de los argumentos de los diferentes teóricos socialistas en ese debate intelectual histórico.`,
            `El libro lleva 7 ediciones (la última en 2024) y es publicado por Unión Editorial. Ha sido traducido al inglés, ruso y chino, entre otros idiomas.`,
        ]
    }
]

export default articles;